version: '3.6'

services:

  customer:
    image: fontys/customer
    ports:
      - "8080:8080"
    restart: on-failure
    build:
      context: ./api/

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=customers
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=